Add embed block for social media embeds
adobe/design-website pull request #307
Opened 2022-07-25 22:37 UTC by arnest00

## Description

Similarly to #301, this PR creates a block for displaying embeds from social media, such as Instagram and Twitter. The block is called `embed` and expects the first and only table cell to contain an embed code.

## Motivation and Context

This will allow content creators to link add social media posts to stories.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

2022-08-04 13:17 UTC, arnest00 commented on blocks/embed/embed.css
> +  margin: 5.25rem 0;
Was requested to match margins for images

2022-08-04 13:18 UTC, arnest00 commented on blocks/embed/embed.js
> +          <blockquote
Embed script replaces internal `blockquote`

2022-08-04 13:19 UTC, arnest00 commented on blocks/embed/embed.js
> +        <blockquote class="twitter-tweet">
Embed script replaces internal `blockquote`

2022-08-05 12:54 UTC, zastrow requested changes
Overall looking good. A few comments. One thing to think about, if you ever have a place where you feel like you need to explain the code in your pull request, it might be good to add the same explanation as a code comment as well.

2022-08-05 12:54 UTC, zastrow commented on blocks/embed/embed.js
> +          <blockquote
Add this as a comment in the code, please.

2022-08-05 12:54 UTC, zastrow commented on blocks/embed/embed.js
> +        <blockquote class="twitter-tweet">
Add this as a comment in the code, please.

2022-08-05 12:54 UTC, zastrow commented on blocks/embed/embed.css
> +  width: 80%;
At 320px wide, which is the smallest and best iPhone size, the Instagram embed is stretching not only beyond the size of the container, but the viewport. The embed has an inline style of `min-width: 326px`:

<img width="378" alt="CleanShot 2022-08-05 at 08 45 24@2x" src="https://user-images.githubusercontent.com/1128391/183080368-3dbec506-f8cf-4e4d-982e-2985428c0d67.png">

Because of this inline-style, the Twitter card is also growing in width outside of the container.
<img width="380" alt="CleanShot 2022-08-05 at 08 45 34@2x" src="https://user-images.githubusercontent.com/1128391/183080960-f720edfb-6df3-474d-9f4a-c8564353a319.png">

The fix is to add a `min-width: unset !important` after the `width: 80%`.

However, after doing that, the width of the instagram embed seems too small. I recommend changing the `width` value to `100%` instead, which would negate the need for the lines 22-26 which changes this value to `100%` at the `900px` media query.

2022-08-05 19:28 UTC, zastrow approved these changes

2022-08-05 19:29 UTC, zastrow commented
✅ Approved! [Great work](https://media.giphy.com/media/26BRBKqUiq586bRVm/giphy.gif), @arnest00

2022-08-09 18:32 UTC, merged