feat: Add images block for side-by-side image embeds
adobe/design-website pull request #310
Opened 2022-07-29 21:54 UTC by arnest00

=## Description

This PR creates a block for displaying two or three images side-by-side. The block is called `images` and expects a single row with either two or three cells. Each cell includes an image and a caption.

## Motivation and Context

This will allow content creators to display up to three images in a row in stories as needed.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

2022-08-02 17:32 UTC, zastrow requested changes
Let’s rename this block to `Multi-Image` so it is clear this is for instances of multiple images. with your Javascript make sure there is a check / fail-safe if less than 2 or more than three images are present.

2022-08-02 17:32 UTC, zastrow commented on blocks/images/images.css
> +  margin: 8.875rem auto;
That is some huge space on smallest screen sizes. appx 320px shown here:
<img width="319" alt="CleanShot 2022-08-02 at 12 59 51@2x" src="https://user-images.githubusercontent.com/1128391/182432246-d1991ca3-d644-4fca-b619-7e328ac42920.png">

Bring this down to maybe half or so. Between `3.5rem` and `4rem` perhaps? And then bump it up in the 900px media query.

2022-08-02 17:32 UTC, zastrow commented on blocks/images/images.css
> +    margin-top: 2.5rem;
Make this `1rem` to match other instances of captions.

2022-08-02 17:32 UTC, zastrow commented on blocks/images/images.css
> +  .cmp-images--3-up .cmp-images__caption {
remove lines 57-61 as they will retain the sizing from the previous media query.

2022-08-05 19:10 UTC, zastrow requested changes
Some minor adjustments to give some larger spacing between stacked images.

2022-08-05 19:10 UTC, zastrow commented on blocks/multi-image/multi-image.css
> +  grid-gap: 12px;
When the images are stacked, they could use a bit more space between them. To get this spacing, it can be done with a larger row gap. If you change the `grid-gap` here to have a value of `2rem 12px` then that will add `2rem` spacing between rows, when there is more than one row.

2022-08-05 19:10 UTC, zastrow commented on blocks/multi-image/multi-image.css
> +.cmp-multi-image__image picture:last-child {
Bt adding the row gap mentioned above, this style is now longer necessary as the larger row gap replaces the function of this selector.

2022-08-05 19:33 UTC, arnest00 commented on blocks/multi-image/multi-image.css
> +.cmp-multi-image__image picture:last-child {
@zastrow Ah, I added this style for a larger buffer between an image without a caption and the image below it. I'll add some reference pictures because design-wise, I'm not sure if it's necessary or not. I did add the row gap, however.

With the buffer:
<img width="677" alt="Screen Shot 2022-08-05 at 12 28 21 PM" src="https://user-images.githubusercontent.com/53844657/183147808-123eb69c-7bd1-470c-b8ba-6ae9de982de9.png">

I'd also modified the selector so the margin isn't added to images that are last in the queue.

```css
.cmp-multi-image__image:not(:last-child) picture:last-child {
  margin-bottom: 1.5rem;
}
```

Without the buffer:
<img width="677" alt="Screen Shot 2022-08-05 at 12 28 58 PM" src="https://user-images.githubusercontent.com/53844657/183147828-f13e220a-6867-4806-8c12-933ef1e14bc6.png">

2022-08-12 16:12 UTC, merged