fix: Pull-quote block not displaying
adobe/design-website pull request #320
Opened 2022-08-29 18:14 UTC by arnest00

## Description

This PR fixes a bug that kept the pull-quote block from rendering as expected.

## Related Issue

[ADB-58](https://sparkbox.atlassian.net/browse/ADB-58)

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

2022-08-30 18:23 UTC, zastrow requested changes
A couple of small changes and then I’m happy to merge this.

2022-08-30 18:23 UTC, zastrow commented on blocks/pull-quote/pull-quote.css
> +  color: #ef6e43;
If this isn’t a CSS Variable in `styles.css`, can that get added?

2022-08-30 18:23 UTC, zastrow commented on blocks/pull-quote/pull-quote.js
> +  const pullQuoteContainer = document.createElement('div');
Since we’re making an element, make it a `blockquote`? It might require a little more CSS to remove some browser defaults.

2022-08-30 18:23 UTC, zastrow commented on blocks/pull-quote/pull-quote.css
> +    margin: 4.375rem 0;
This is the one thing Andrea was wondering about and posted an image of the comp in Slack. Double check that the spacing looks right. I feel like it looked close.

2022-08-30 20:26 UTC, arnest00 commented on blocks/pull-quote/pull-quote.css
> +    margin: 4.375rem 0;
For reference,

From the preview page:
<img width="1496" alt="Screen Shot 2022-08-30 at 1 10 09 PM" src="https://user-images.githubusercontent.com/53844657/187534991-6f318afb-f94b-4a9c-974d-bcdf9cbdb847.png">

From Slack:
<img width="585" alt="Screen Shot 2022-08-30 at 11 58 52 AM" src="https://user-images.githubusercontent.com/53844657/187535098-881f4653-7aa8-434f-bf1d-5c05009d7c9f.png">

No indentation, same margins as the text.

2022-08-31 18:11 UTC, zastrow approved these changes

2022-08-31 18:12 UTC, closed without merging